# Generated by Django 5.0.7 on 2024-07-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="pseudo",
            new_name="username",
        ),
    ]
